### ISSUE TITLE
Can this be used for TMS-style HTTP requests?

### ISSUE THREAD

**Issue by tombh** [pedros007/mapserver-docker#1]
I mean something like `/{x}/{y}/{z}`?

I'm wondering if such a thing is possible for Cloud Optimized GeoTiffs? I know there's also https://github.com/hotosm/oam-dynamic-tiler (which I'm helping with), but it doesn't support GeoTiffs as far as I know yet.

**Comment by pedros007** [comment]
Hi @tombh. As far as I know, Mapserver does not have a TMS/WTMS endpoint. In the past, I've put a lightweight proxy in front of WMS that would take `/{x}/{y}/{z}/` coordinates and proxy to WMS. Check out [ZXY to WMS Proxy](http://fuzzytolerance.info/blog/2016/03/15/ZXY-to-WMS-Proxy/).

If your site will be high traffic, you may want to check out something like [MapCache](http://mapserver.org/mapcache/) or [MapProxy](https://mapproxy.org/) which can act like a TMS -> WMS proxy, while also caching the resulting images.

**Comment by tombh** [comment]
Great answer, that's given me lots to research and think about, thank you :)
